#!/bin/bash
# Author
# Date Created: 03/04/2023
# Descripition: Create Input-output
# Date Modified: 03/04/2023
a=`hostname`
echo Hello, my server name is $a
echo
echo what is your name?
read b
echo
echo what is your profession?
read c
echo what is your favourite show?
read d
echo
echo Hello $b
echo your profession $c is awesome
echo $d is a good show
echo
